#
# This application allows forwarding e-mails
# stored by AWS SES or other applications in
# an S3 bucket to destination emails configured
# in the environment variables
# 
AWSTemplateFormatVersion: 2010-09-09
Description: "AWS SES E-Mail Forwarding"

Parameters:
    # this address will be used as the sender
    # and the original address will be put into
    # the reply-to header
    SenderMailAddress:
        Description: "Default sender address for forwarding"
        Type: String
        Default: "forward@mydomain.com"

    # default recipient is used when no other
    # email address matches the query (catch-all)
    DefaultRecipientMailAddress:
        Description: "Default recipient address for forwarding"
        Type: String
        Default: "catchall@mydomain.com"

    # the name of the s3 bucket that holds all
    # the raw emails collected by SES or others
    EmailBucketName:
        Description: "Name of the S3 bucket with the mails"
        Type: String
        Default: "my-email-s3-bucket"

Resources:
    # IAM role for the lambda function
    LambdaRole:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument:
                Version: 2012-10-17
                Statement:
                - Effect: Allow
                  Principal:
                    Service:
                      - lambda.amazonaws.com
                  Action:
                    - 'sts:AssumeRole'
            Path: /
            Policies:
                - PolicyName: root
                  PolicyDocument:
                    Version: 2012-10-17
                    Statement:
                    - Effect: Allow
                      Action:
                        - 's3:*'
                      Resource: '*'
                    - Effect: Allow
                      Action:
                        - 'ses:SendRawEmail'
                      Resource: '*'
                    - Effect: Allow
                      Action:
                        - 'logs:CreateLogGroup'
                        - 'logs:CreateLogStream'
                        - 'logs:PutLogEvents'
                      Resource: 'arn:aws:logs:*:*:*'

    # invoke permission for s3 calling lambda
    LambdaInvokePermission:
        Type: AWS::Lambda::Permission
        Properties:
            FunctionName: !GetAtt LambdaFunction.Arn
            Action: 'lambda:InvokeFunction'
            Principal: s3.amazonaws.com
            SourceAccount: !Ref 'AWS::AccountId'
            SourceArn: !Sub 'arn:aws:s3:::${EmailBucketName}'

    # trigger calling lambda for new s3 objects
    LambdaTrigger:
        Type: Custom::RouteTableLambda
        DependsOn: LambdaInvokePermission
        Properties:
            ServiceToken: !GetAtt LambdaFunction.Arn
            LambdaArn: !GetAtt LambdaFunction.Arn
            Bucket: !Ref EmailBucketName

    # lambda function that processes the forwarding
    LambdaFunction:
        DependsOn:
        - LambdaRole
        Type: AWS::Lambda::Function
        Properties:
            Handler: 'app.lambdaHandler'
            Role: !GetAtt LambdaRole.Arn
            Runtime: 'nodejs12.x'
            Timeout: 60
            Environment:
                Variables:
                    SENDER_ADDRESS: !Ref SenderMailAddress
                    DEFAULT_RECIPIENT: !Ref DefaultRecipientMailAddress
            Code:
                ZipFile: "const AWS=require(\"aws-sdk\");async function forwardMessage(e){let r=new AWS.S3,t=await r.getObject({Bucket:e.s3.bucket.name,Key:e.s3.object.key}).promise();if(null!==t){let e=rewriteMessage(t.Body.toString(\"ascii\")),r=new AWS.SES({apiVersion:\"2010-12-01\"});await r.sendRawEmail({RawMessage:{Data:e}}).promise()}}function rewriteMessage(e){let r=\"From: \"+process.env.SENDER_ADDRESS+\"\\r\\n\",t=e.substring(0,e.indexOf(\"\\r\\n\\r\\n\")),n=\/^To:(.*)$\/gim.exec(t);null!==n&&2===n.length&&(r+=\"To: \"+getTargetMailAddress(n[1].trim())+\"\\r\\n\");let s=\/^Subject:(.*)$\/gim.exec(t);null!==s&&2===s.length&&(r+=\"Subject: \"+s[1].trim()+\"\\r\\n\");let o=\/^From:(.*)$\/gim.exec(t);null!==o&&2===o.length&&(r+=\"Reply-To: \"+o[1].trim()+\"\\r\\n\");let i=\/^Content-Type:(.*)$\/gim.exec(t);return null!==i&&2===i.length&&(r+=\"Content-Type: \"+i[1].trim()+\"\\r\\n\"),r+=e.substr(e.indexOf(\"\\r\\n\\r\\n\"))}function getTargetMailAddress(e){let r=process.env.DEFAULT_RECIPIENT;for(let t in process.env)if(t.startsWith(\"forward-from:\")){t.split(\":\")[1].trim().toLowerCase()===e.toLowerCase()&&(r=process.env[t])}return r}exports.lambdaHandler=(async(e,r)=>{let t=[];if(e.hasOwnProperty(\"Records\")){e.Records.length>0&&AWS.config.update({region:e.Records[0].awsRegion});for(let r=0;r<e.Records.length;r++)t.push(forwardMessage(e.Records[r]))}return await Promise.all(t),!0});"